/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto_Agenda_Tela;

import Projeto_Agenda_Classe.Contacto_Classe;
import Projeto_Agenda_Classe.Endereco_Classe;
import Projeto_Agenda_Classe.Usuario_Classe;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author cg3017885
 */
public class Cadastro_Tela extends javax.swing.JFrame {
    ArrayList<Usuario_Classe> CadUsuario = new ArrayList<Usuario_Classe>(1);
    ArrayList<Contacto_Classe> CadContacto = new ArrayList<Contacto_Classe>(1);
    ArrayList<Endereco_Classe> CadEndereco = new ArrayList<Endereco_Classe>(1);
   
    private String Usuario;
    private String Senhahex;
    private String SenhahexConfirm;
    
    private String Nome;
    private Date Data_nasc;
    private long Telefone1;
    private long Telefone2;
    private String Email;
    
    private String Logradouro; 
    private String Bairro;
    private int CEP;
    private String Complemento;
    private String Cidade;     
    private String Sigla_estado;
    
    public Cadastro_Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotaoProximo1 = new javax.swing.JButton();
        CriarUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotaoVoltarLogin = new javax.swing.JButton();
        CriarSenha = new javax.swing.JPasswordField();
        CriarConfirmarSenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotaoAnterior1 = new javax.swing.JButton();
        BotaoProximo2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CriarNomeUsuario = new javax.swing.JTextField();
        CriarEmailUsuario = new javax.swing.JTextField();
        CriarTelefone1Usuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CriarTelefone2Usuario = new javax.swing.JTextField();
        CriarDataNasc = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        BotaoAnterior2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CriarLogradouroUsuario = new javax.swing.JTextField();
        CriarCEPUsuario = new javax.swing.JTextField();
        CriarComplementoUsuario = new javax.swing.JTextField();
        BotaoConcluirCadastro = new javax.swing.JButton();
        CriarCidadeUsuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CriarEstadoUsuario = new javax.swing.JComboBox<>();
        CriarBairroUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 255, 255));
        jTabbedPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Criação do Usuário");

        BotaoProximo1.setBackground(new java.awt.Color(102, 255, 255));
        BotaoProximo1.setText("Próximo");
        BotaoProximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProximo1ActionPerformed(evt);
            }
        });

        CriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel4.setText("Senha");

        jLabel5.setText("Confirmação de Senha");

        BotaoVoltarLogin.setBackground(new java.awt.Color(102, 255, 255));
        BotaoVoltarLogin.setText("Voltar ao Login");
        BotaoVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarLoginActionPerformed(evt);
            }
        });

        CriarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoVoltarLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoProximo1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 178, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(167, 167, 167))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CriarUsuario)
                    .addComponent(CriarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(CriarConfirmarSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(CriarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CriarConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoProximo1)
                    .addComponent(BotaoVoltarLogin))
                .addContainerGap())
        );

        jTabbedPane1.addTab("1", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Dados do Usuário");

        BotaoAnterior1.setBackground(new java.awt.Color(102, 255, 255));
        BotaoAnterior1.setText("Anterior");
        BotaoAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAnterior1ActionPerformed(evt);
            }
        });

        BotaoProximo2.setBackground(new java.awt.Color(102, 255, 255));
        BotaoProximo2.setText("Próximo");
        BotaoProximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProximo2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome Completo");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("E-mail");

        jLabel9.setText("Telefone 1");

        CriarNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel14.setText("Telefone 2");

        CriarTelefone2Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarTelefone2UsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BotaoAnterior1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoProximo2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 108, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(CriarTelefone2Usuario))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(CriarEmailUsuario))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(CriarNomeUsuario))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(CriarDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(CriarTelefone1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CriarNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CriarDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CriarEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CriarTelefone1Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CriarTelefone2Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAnterior1)
                    .addComponent(BotaoProximo2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        BotaoAnterior2.setBackground(new java.awt.Color(102, 255, 255));
        BotaoAnterior2.setText("Anterior");
        BotaoAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAnterior2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Endereço");

        jLabel11.setText("Logradouro");

        jLabel12.setText("CEP");

        jLabel13.setText("Complemento");

        BotaoConcluirCadastro.setBackground(new java.awt.Color(102, 255, 255));
        BotaoConcluirCadastro.setText("Concluir");
        BotaoConcluirCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConcluirCadastroActionPerformed(evt);
            }
        });

        CriarCidadeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarCidadeUsuarioActionPerformed(evt);
            }
        });

        jLabel15.setText("Cidade");

        CriarEstadoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        CriarEstadoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarEstadoUsuarioActionPerformed(evt);
            }
        });

        CriarBairroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarBairroUsuarioActionPerformed(evt);
            }
        });

        jLabel16.setText("Bairro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoAnterior2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CriarBairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CriarLogradouroUsuario)
                                    .addComponent(CriarCEPUsuario)
                                    .addComponent(CriarComplementoUsuario)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(CriarCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CriarEstadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BotaoConcluirCadastro)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CriarLogradouroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarBairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarCEPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CriarComplementoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarCidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(CriarEstadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoAnterior2)
                    .addComponent(BotaoConcluirCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("3", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoProximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProximo1ActionPerformed
        Usuario = CriarUsuario.getText();
        
        Usuario_Classe loginUsuario = new Usuario_Classe(this.Usuario,this.Senhahex);
        
        CadUsuario.add(loginUsuario);
        
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BotaoProximo1ActionPerformed

    private void BotaoAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAnterior1ActionPerformed
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_BotaoAnterior1ActionPerformed

    private void BotaoProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoProximo2ActionPerformed
        Nome = CriarNomeUsuario.getText();
        Data_nasc = CriarDataNasc.getDate();
        Telefone1 = Long.parseLong(CriarTelefone1Usuario.getText());
        
        if(CriarTelefone2Usuario.getText().isEmpty()){
            Telefone2 = 0;
        }else{       
            Telefone2 = Integer.parseInt(CriarTelefone2Usuario.getText()); 
        }
        Email = CriarEmailUsuario.getText();
        
        Usuario_Classe DadosUsuario = new Usuario_Classe(this.Nome, this.Data_nasc);
        Contacto_Classe DadosComunic = new Contacto_Classe (this.Telefone1, this.Telefone2, this.Email);
        
        CadContacto.add(DadosComunic);
        CadUsuario.add(DadosUsuario);
        CadUsuario.get(0).setNomeU(Nome);
        CadUsuario.get(0).setData_nascU(Data_nasc);
        
        this.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_BotaoProximo2ActionPerformed

    private void BotaoAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAnterior2ActionPerformed
        this.jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BotaoAnterior2ActionPerformed

    private void CriarNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarNomeUsuarioActionPerformed

    private void BotaoConcluirCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConcluirCadastroActionPerformed

        Logradouro = CriarLogradouroUsuario.getText();
        Bairro = CriarBairroUsuario.getText();
        CEP = Integer.parseInt(CriarCEPUsuario.getText());
        Complemento = CriarComplementoUsuario.getText();
        Cidade = CriarCidadeUsuario.getText();
        Sigla_estado = CriarEstadoUsuario.getSelectedItem().toString();
        
        Endereco_Classe DadosEnd = new Endereco_Classe(this.Logradouro, this.Bairro, this.CEP, this.Complemento, this.Cidade, this.Sigla_estado);
        CadEndereco.add(DadosEnd);
        
        Login_Tela logintela = new Login_Tela();

        this.setVisible(false);
        logintela.setLocationRelativeTo(null);
        logintela.setVisible(true);
    }//GEN-LAST:event_BotaoConcluirCadastroActionPerformed

    private void BotaoVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarLoginActionPerformed
        Login_Tela logintela = new Login_Tela();

        this.setVisible(false);
        logintela.setLocationRelativeTo(null);
        logintela.setVisible(true);
    }//GEN-LAST:event_BotaoVoltarLoginActionPerformed

    private void CriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarUsuarioActionPerformed

    private void CriarTelefone2UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarTelefone2UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarTelefone2UsuarioActionPerformed

    private void CriarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarSenhaActionPerformed

    private void CriarEstadoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarEstadoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarEstadoUsuarioActionPerformed

    private void CriarCidadeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarCidadeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarCidadeUsuarioActionPerformed

    private void CriarBairroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarBairroUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarBairroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAnterior1;
    private javax.swing.JButton BotaoAnterior2;
    private javax.swing.JButton BotaoConcluirCadastro;
    private javax.swing.JButton BotaoProximo1;
    private javax.swing.JButton BotaoProximo2;
    private javax.swing.JButton BotaoVoltarLogin;
    private javax.swing.JTextField CriarBairroUsuario;
    private javax.swing.JTextField CriarCEPUsuario;
    private javax.swing.JTextField CriarCidadeUsuario;
    private javax.swing.JTextField CriarComplementoUsuario;
    private javax.swing.JPasswordField CriarConfirmarSenha;
    private com.toedter.calendar.JDateChooser CriarDataNasc;
    private javax.swing.JTextField CriarEmailUsuario;
    private javax.swing.JComboBox<String> CriarEstadoUsuario;
    private javax.swing.JTextField CriarLogradouroUsuario;
    private javax.swing.JTextField CriarNomeUsuario;
    private javax.swing.JPasswordField CriarSenha;
    private javax.swing.JTextField CriarTelefone1Usuario;
    private javax.swing.JTextField CriarTelefone2Usuario;
    private javax.swing.JTextField CriarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
