package Projeto_Agenda_Tela;

/**
 * @author Eduardo Luiz Sales do Prado / João Pedro Bettin de Souza
 */
import Projeto_Agenda_Classe.ConnectionFactory;
import java.awt.Color;
import java.awt.Dimension;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.security.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;

public class Login_Tela extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login_Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InserirUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BotaoAcessar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        BotaoIrCadastro = new javax.swing.JButton();
        InserirSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 250));

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        InserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Login");

        BotaoAcessar.setBackground(new java.awt.Color(102, 255, 255));
        BotaoAcessar.setText("Acessar");
        BotaoAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcessarActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 153));
        jCheckBox1.setText("Lembrar de Mim");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        BotaoIrCadastro.setBackground(new java.awt.Color(102, 255, 255));
        BotaoIrCadastro.setText("Não Possue conta?");
        BotaoIrCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIrCadastroActionPerformed(evt);
            }
        });

        InserirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InserirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(InserirSenha)))
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotaoIrCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(BotaoAcessar)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InserirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InserirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAcessar)
                    .addComponent(BotaoIrCadastro))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con;
    private void InserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirUsuarioActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void BotaoIrCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIrCadastroActionPerformed
<<<<<<< HEAD
        Cadastro_Tela cadastrotela = new Cadastro_Tela();

=======
        Cadastro_Tela cadastroVamos = new Cadastro_Tela();
        
>>>>>>> 501a5162c3b09f98f3e0d0b9e21870854171c59f
        this.setVisible(false);
        cadastroVamos.setVisible(true);
    }//GEN-LAST:event_BotaoIrCadastroActionPerformed

    private void BotaoAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcessarActionPerformed
<<<<<<< HEAD
        String query = "SELECT UsuarioNome, Senha from Usuario WHERE IdUsuario = \"1\" AND UsuarioNome = ? AND Senha = ?;";
        PreparedStatement ps;
        ResultSet rs;
        String usuario = this.InserirUsuario.getText();
        try {
            MessageDigest cryptSenha = MessageDigest.getInstance("SHA-256");
            byte messageDigestSenha[] = cryptSenha.digest(String.valueOf(this.InserirSenha.getPassword()).getBytes("UTF-8"));

            StringBuilder hexString = new StringBuilder();
            for (byte b : messageDigestSenha) {
                hexString.append(String.format("%02X", 0xFF & b));
            }
            String senha_string = hexString.toString();

            ConnectionFactory cf = new ConnectionFactory();
            con = cf.getConnection();
            con.setAutoCommit(false);
            ps = con.prepareStatement(query);
            ps.setString(1, usuario);
            ps.setString(2, senha_string);
            rs = ps.executeQuery();
            con.commit();

            int idUsuario = 0;
            String usuarioBD = "";
            String senhaBD = "";

            while (rs.next()) {
                idUsuario = rs.getInt("IdUsuario");
                usuarioBD = rs.getString("UsuarioNome");
                senhaBD = rs.getString("Senha");
            }

            if (usuarioBD == "") {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos");
            } else {
                System.out.println(usuarioBD);
            }

            ps.close();

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Login_Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login_Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotaoAcessarActionPerformed

    private void InserirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InserirSenhaActionPerformed

=======
        PaginaPrincpalAgenda_Tela AgendaPrincipal = new PaginaPrincpalAgenda_Tela() ;
        
        this.setVisible(false);
        AgendaPrincipal.setLocationRelativeTo(null);
        AgendaPrincipal.setVisible(true);
    }//GEN-LAST:event_BotaoAcessarActionPerformed

>>>>>>> 501a5162c3b09f98f3e0d0b9e21870854171c59f
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Tela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Tela().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAcessar;
    private javax.swing.JButton BotaoIrCadastro;
    private javax.swing.JPasswordField InserirSenha;
    private javax.swing.JTextField InserirUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
